version: '3.4'

services:
  cuentadb:
    image: postgres:17.11-alpine3.24

  pgadmin:
    image: dpage/pgadmin4

  client.api:
    image: ${DOCKER_REGISTRY-}clientapi
    build:
      context: .
      dockerfile: Services/Cliente/Client.API/Dockerfile

  account.api:
    image: ${DOCKER_REGISTRY-}accountapi
    build:
      context: .
      dockerfile: Services/Cuenta/Account.API/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile

volumes:
  postgres_cuenta:
  pg_adminCuenta:

